version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - ai-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=agent
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  mongo_data: